## Jira Properties
systemProp.jira.username=dqqajira
systemProp.jira.password=Infa@2019

## Project Information
systemProp.PROJECT_NAME=Cloud Data Governance & Catalog
systemProp.PROJECT_VERSION=2024.02.S

##ZAPI import test cases details
## cloud  project details
systemProp.jira.version=2024.02.S
systemProp.jira.projectName=Cloud Data Governance & Catalog
systemProp.jira.issueTypeId=13701
systemProp.jira.versionId=
systemProp.jira.projectId=26760


systemProp.featurefilePath=C:\\Users\\pdewanga\\Perforce\\pdewanga_search_Feature_Branch\\restapi-test\\src\\test\\resources\\Search_New_Cases\\Neo4j_KGS_New_2.feature

##Provide comma seperated values for feature files EX: C:\\Users\\vkr\\Documents\\ZypherJiraTestsCreation\\demoZapiNewCopy1.feature,d1\\demoZapi.feature,d2\\demo.feature  ,demoZapiNewCopy1.feature,demoZapiNew.feature,
#C:\\Users\\vkr\\Perforce\\vkr_INW1PF0YDA9L_vkr_IMS_500\\restapi-test\\src\\test\\resources\\issueManagementService\\